import { createContext, useCallback, useContext, useMemo } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { authApi } from '@/api/endpoints';
import { tokenStorage } from '@/services/tokenStorage';
import type { LoginRequest, UserMe } from '@/types/api';
interface AuthContextValue { user?: UserMe; isLoading: boolean; isAuthenticated: boolean; login: (payload: LoginRequest) => Promise<void>; logout: () => Promise<void>; hasPermission: (permission: string) => boolean; hasRole: (role: string) => boolean }
const AuthContext = createContext<AuthContextValue | undefined>(undefined);
export function AuthProvider({ children }: { children: React.ReactNode }) { const qc = useQueryClient(); const enabled = Boolean(tokenStorage.getAccessToken()); const me = useQuery({ queryKey: ['auth','me'], queryFn: authApi.me, enabled, retry: false }); const loginMutation = useMutation({ mutationFn: authApi.login, onSuccess: (tokens) => { tokenStorage.setTokens(tokens.access_token, tokens.refresh_token); void qc.invalidateQueries({ queryKey: ['auth'] }); } }); const login = useCallback(async (payload: LoginRequest) => { await loginMutation.mutateAsync(payload); }, [loginMutation]); const logout = useCallback(async () => { const refresh = tokenStorage.getRefreshToken(); if (refresh) await authApi.logout(refresh).catch(()=>undefined); tokenStorage.clear(); qc.clear(); }, [qc]); const value = useMemo<AuthContextValue>(() => ({ user: me.data, isLoading: me.isLoading || loginMutation.isPending, isAuthenticated: Boolean(me.data), login, logout, hasPermission: (permission) => me.data?.permissions.includes(permission) ?? false, hasRole: (role) => me.data?.roles.includes(role) ?? false }), [me.data, me.isLoading, loginMutation.isPending, login, logout]); return <AuthContext.Provider value={value}>{children}</AuthContext.Provider>; }
export function useAuth() { const value = useContext(AuthContext); if (!value) throw new Error('useAuth must be used within AuthProvider'); return value; }
